# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Auth

# Model Form Field configuration
form: $/crazy/backend/models/auth/fields.yaml

# Model Class name
modelClass: Crazy\Backend\Models\Auth

# Default redirect location
defaultRedirect: crazy/backend/auth

# Create page
create:
    title: backend::lang.form.create_title
    redirect: crazy/backend/auth/update/:id
    redirectClose: crazy/backend/auth

# Update page
update:
    title: backend::lang.form.update_title
    redirect: crazy/backend/auth
    redirectClose: crazy/backend/auth

# Preview page
preview:
    title: backend::lang.form.preview_title
